apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
data:
    api-token: ENC[AES256_GCM,data:WscmNbWFWv481YDrpPUIdoqVTwH32lkziA9EfHFLr92C7mWSAc5EPkcxZ973K4T2p/K9oyj8a6k=,iv:IqsIlEzs9xR8GFU5t9ZUrpjozVw7dyIHH7R+8HeJVB4=,tag:CTFwNzDGPVnKyIaqmIT0Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16hx09qhepk5m55yqf8mseghqzsjzzxfu4d4qa59w5djj2tvhsq5qjcl2z8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcnRPVW9IeTdZWEwzcXJB
            NTMyN2dxUHFoanB6bU9wTmFMNzk0RkNrQkEwCnpZa0NsaFBVQ0M1c0pyZ0FEeEI1
            TkN6NzkxZVRST241V3ZlaVpCVFVlSzAKLS0tIERyZXM2VmdKdmpYZEZkaDNaRW9w
            dTVkbVhwak52RGg5Y245Y3dpOENKSWMKxDM4SVuNM8UEdZM/DBd54r67+fFCtO/S
            pGAjoXuFamqkjkbs62gyu61EBRX9tWXIlbSGWoPOMOZIbsOVEIUD0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-25T17:30:08Z"
    mac: ENC[AES256_GCM,data:v/JJHCXIcaHaXN6Nj1/kXYibl2cCB+FuklUDZnxrNEWna+L6skCAFe4Wv7LCnZWf5YPKco+eX6fTA7O+v9RFZKvHMmZac4/OkT66mioreaWwX1yUL9v2Gqdhvcl7nZpQlRrwbQP0rJUKe57DEbd5phiFKclLs5dg6PQaqp/Cf9c=,iv:18wdYLZ6f1GPXGTteivDnof464omF0AzY4lYajyXxxk=,tag:8MDaOIYRdAW7T54rAeTEFA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
