---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: cluster-orchestration
    namespace: flux-system
spec:
    interval: 10m0s
    dependsOn:
        - name: cluster-repositories
        - name: cluster-flux
    path: ./kubernetes/clusters/home-prod/flux/orchestration
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
    decryption:
        provider: sops
        secretRef:
            name: sops-age
    patches:
        - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
              kind: Kustomization
              metadata:
                name: NOOP
                namespace: NOOP
              spec:
                decryption:
                  provider: sops
                  secretRef:
                    name: sops-age
          target:
              kind: Kustomization
              group: kustomize.toolkit.fluxcd.io
              version: v1beta2
