apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-flux
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-repositories
  interval: 10m0s
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux