---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: emissary-ingress-source
  namespace: flux-system
spec:
  interval: 30m
  # renovate: registryUrl=https://app.getambassador.io chart=emissary-ingress
  url: https://github.com/emissary-ingress/emissary.git
  ref:
    tag: chart-v7.1.9
  ignore: |
    /*
    !/charts/emissary-ingress/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emissary-ingress-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: emissary-ingress-source