apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
spec:
  chart:
    spec:
      # renovate: registryUrl=https://app.getambassador.io
      chart: emissary-ingress
      version: 7.1.8-ea
      sourceRef:
        kind: HelmRepository
        name: datawire
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    force: true
  interval: 10m0s
