apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: 1.41.0
  values:
    deployment:
      instance_name: kiali
    auth:
      strategy: anonymous
  interval: 10m0s
