apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kiali.org/helm-charts
      chart: kiali-server
      version: 1.41.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kiali-values
  interval: 10m0s
