apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.5.3
  values:
    installCRDs: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
