---
ci:
  submodules: true
repos:
    - repo: https://github.com/psf/black
      rev: 21.10b0
      hooks:
          - id: black

    - repo: https://github.com/google/go-jsonnet
      rev: b10eae7c683a26fad7f7fe53f9772c806f81a0b0
      hooks:
          - id: jsonnet-format
          # Disabled temporarily due to https://github.com/google/go-jsonnet/issues/544
          #- id: jsonnet-lint
            #args: [-J, kubernetes/config/lib]

    - repo: local
      hooks:
          - id: generate-manifests
            name: Generate manifests
            description: This hook compiles Jsonnet manifests into raw YAML.
            entry: scripts/gen_configs.py
            language: script
            always_run: true
            pass_filenames: false

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
            args: ['-m']
          - id: check-json
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
