---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
    - helm-release.yaml
configMapGenerator:
    - name: cilium-infrastructure-values
      files:
          - values.yaml
configurations:
    - kustomizeconfig.yaml
