---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-source
  namespace: flux-system
spec:
  interval: 30m
  # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts chart=base
  url: https://github.com/istio/istio.git
  ref:
    tag: 1.11.4
  ignore: |
    /*

    # Base chart CRDs
    !/manifests/charts/base/crds/*.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: istio-source