apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base
spec:
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: base
      version: 1.12.0-beta.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 10m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: istiod
      version: 1.12.0-beta.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 10m0s
