---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: home-k8s
spec:
    ignore: "/*\n!/kubernetes/_gen/common\n!/kubernetes/_gen/clusters/home-prod\n"
    interval: 1m0s
    ref:
        branch: trunk
    url: https://github.com/remi-gelinas/home-k8s.git
