---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: cluster-deployment
    namespace: fluxcd.io-system
spec:
    interval: 10m0s
    path: ./kubernetes/clusters/home-prod/fluxcd.io/deploy
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
