apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io/
      chart: cilium
      version: 1.10.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  upgrade:
    force: true
  valuesFrom:
    - kind: ConfigMap
      name: cilium-base-values
  interval: 10m0s
