---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: emissary-ingress-crds
    namespace: flux-system
spec:
    interval: 15m
    prune: false
    sourceRef:
        kind: GitRepository
        name: emissary-ingress-source
    wait: true
