---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: cluster-repositories
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./kubernetes/_gen/clusters/home-prod/flux/repositories
    prune: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
    wait: true
