---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: cluster-orchestration
    namespace: flux-system
spec:
    decryption:
        provider: sops
        secretRef:
            name: sops-age
    dependsOn:
        - cluster-repositories
        - cluster-flux
    interval: 10m0s
    path: ./kubernetes/_gen/clusters/home-prod/flux/orchestration
    prune: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
    wait: true
