apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: istio
  path: ./kubernetes/clusters/home-prod/apps/kiali
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
