---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: cert-manager-common
    namespace: fluxcd.io-system
spec:
    interval: 10m0s
    path: ./kubernetes/common/infrastructure/cert-manager
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: emissary-ingress-common
    namespace: fluxcd.io-system
spec:
    interval: 10m0s
    path: ./kubernetes/common/infrastructure/emissary-ingress
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: istio-common
    namespace: fluxcd.io-system
spec:
    interval: 10m0s
    path: ./kubernetes/common/infrastructure/istio
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: home-k8s
