apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/home-prod/infrastructure/cert-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emissary-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager
  path: ./kubernetes/clusters/home-prod/infrastructure/emissary-ingress
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/home-prod/infrastructure/istio
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-k8s