apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: home-k8s
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: trunk
  url: https://github.com/remi-gelinas/home-k8s.git
  ignore: |
    /*
    !/kubernetes/common
    !/kubernetes/clusters/home-prod