apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: home-ops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: trunk
  url: https://github.com/remi-gelinas/homelab.git
  ignore: |
    /*
    !/kubernetes/common
    !/kubernetes/clusters/home-prod