apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    api-token: AgBgBLP2w9MxwVrdefp9hfGAArk4ZwU3DqybaKBY0fyHsem4rkOIf7xmSgYe3jfVZCiBjU5X0U2kHEUqBp3voeFxJpXYDUfhlQs5f36sw7IkU0oJePUcFQNqcuTQNQXuy8FaPks63a2rNDXI5hKmHUYSUl2bLTGKZ8HSG306Bjb2w2Cm7y4ygLNX4ZpWa56dMqFXvhgi1hhNOqwFPQEODJJvUdlG0fwToTy8V3x19H4GC5OZjy+UhvWWo/u7NZ1MrwA41VKfSyhVsrn/4DChdSNMK0mSCMMR6tReXj5TTlK7GPgK9CeRYFyq7+I6HJrcLVBV98Of60kgeTGfWTkHWfgOGZl7fpI9X2wGtqXdUwNzCLvNOdnXs1h6YxGu/KElNkIbbnG4WK1jCA/v1NJUfRahpnsazZ+lr2li1zpOSGn2Q7eMT97+RyptauX9FDWcoKOFLd/Y/UwOi/YhxLfbGt6ebma0EEvc351DjbQkM3uOEojsHkdToufgwlI9ORnX73zFqsXi9Aweu9Zu9wc5juMfsxATMxhxktleowntoDYQfNfIwjA4Z3Irez26N3airlBA08RLnv26QUbgIkMGSslnTlX4neNNwgCDdocq/FUjeirq1RVWRalIJfumWIFeyuI8/L0u1vowIYJpPikKwAjGRWlN7sfxR82Ptb73pDvT44MCvKFDGXAvoURaXYx4L3Ysw+z28QxCW/ScBArlRZZ+l0FLabVBFpI8DVInK9iQr9YZ5RoecCRx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

