apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base
spec:
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.12.0-alpha.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.12.0-alpha.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cni
spec:
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.12.0-alpha.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
