apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: mail@remigelin.as
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: mail@remigelin.as
            apiKeySecretRef:
              name: cloudflare-api-key
              key: apikey
          selector:
            dnsZones:
              - "gelinas.cloud"