---
# Shamelessly modified from https://github.com/onedr0p/home-cluster/blob/main/.github/workflows/diff-helm-releases.yaml
name: Diff Helm Releases on Pull Requests

on:
    pull_request:
        branches:
            - trunk
        paths:
            - kubernetes/config/**.jsonnet
            - kubernetes/config/**.libsonnet

jobs:
    changes:
        name: Detect changes
        runs-on: ubuntu-20.04
        outputs:
            files: ${{ steps.extract.outputs.files }}
        steps:
            - uses: actions/checkout@v2
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  list-files: shell
                  filters: |
                      changed:
                        - '**'
            - id: extract
              run: |
                  filtered=$(grep -zl "// renovate: helmChartVar" ${{ steps.filter.outputs.changed_files }} \
                    | jq -nR '[inputs | select(length>0)]')
                  echo ::set-output name=files::${filtered}

    helm-release-diff:
        name: Template Helm Releases
        runs-on: ubuntu-20.04
        if: ${{ needs.changes.outputs.files != '' }}
        needs:
            - changes
        strategy:
            matrix:
                file: ${{ fromJson(needs.changes.outputs.files) }}
            fail-fast: false
        steps:
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: ^1

            - name: Install Jsonnet
              run: go get github.com/google/go-jsonnet/cmd/jsonnet

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip

            - uses: azure/setup-helm@v1
              id: install_helm

            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.base.sha }}
                  path: live
                  submodules: recursive

            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  path: pr
                  submodules: recursive

            - id: diff
              run: |
                  message=$(python scripts/diff_helm_releases.py live/${{ matrix.file }} pr/${{ matrix.file }} ${{ steps.install_helm.outputs.helm-path }})
                  echo "::set-output name=message::$(echo "$message" | jq --raw-input --slurp)"

            - uses: peter-evans/create-or-update-comment@v1
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: ${{ fromJSON(steps.diff.outputs.message) }}
