name: pre-commit-fix-prs

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - trunk

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Install Jsonnet
        run: go get github.com/google/go-jsonnet/cmd/jsonnet

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install ruamel.yaml

      - name: Cache pre-commit environments
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pre-commit-envs-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit

      - name: Run pre-commit
        run: pre-commit run

      - name: Update pull request if needed
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fix: add pre-commit changes'
